name: jobtinder
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flare_flutter: ^1.5.1
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  graphql_flutter: ^1.0.1
  shared_preferences: ^0.5.3+1
  provider: 3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    # Animations
    - assets/animations/login.flr

    # Images
    - assets/images/login_background.jpg
  
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

    - family:  Custom
      fonts:
       - asset: assets/fonts/Custom.ttf
    
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 200